title: 张海云
description: My Personal Stack Problems
author: 张海云
github: https://github.com/seeacloud
about: 不想做全栈的前端不是好设计...
disqus_shortname: 前端笔记本...
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

# social:
#     - icon: fa-facebook
#       link: "#"
#     - icon: fa-skype
#       link: "#"
#     - icon: fa-twitter
#       link: "https://twitter.com/agusmakmun6"
#     - icon: fa-linkedin
#       link: "#"
#     - icon: fa-stack-exchange
#       link: "#"

# share:
#   twitter_username: agusmakmun6
#   fb_appid: 1749788565247320

urls:
    - text: 我是谁？
      url: /about/
    - text: 项目
      url: /projects/
    - text: Github
      url: https://github.com/seeacloud
    # - text: XML Feed
    #   url: /feed.xml

url: "https://seeacloud.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist